[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.11"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
astrolend = "Astro1oWvtB7cBTwi3efLMFB47WXx7DJDQeoxi235kA"

[provider]
cluster = "https://eclipse.helius-rpc.com"
wallet = "~/.config/solana/id.json"
